data:
  image: busybox
  volumes:
    - ~/Docker/redmine/data/var/lib/mysql/:/var/lib/mysql/
    - ~/Docker/redmine/data/usr/src/redmine/files/:/usr/src/redmine/files/
    - ~/Docker/redmine/data/usr/src/redmine/plugins/:/usr/src/redmine/plugins

web:
  image: redmine
  volumes_from:
    - data
  environment:
    VIRTUAL_HOST: my.redmine
  links:
    - db:mysql

db:
  image: mysql:5.5
  volumes_from:
    - data
  environment:
    MYSQL_ROOT_PASSWORD: redmine@pass
    MYSQL_DATABASE: redmine
